# Generated by Django 3.2.9 on 2022-02-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookings',
        ),
    ]
